
import { Plus, Trash2 } from "lucide-react";
const uniqueId = (prefix) => `${prefix}-${crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const makeAttribute = () => ({ id: uniqueId("attr"), visibility: "private", name: "field", type: "String" });
const makeMethod = () => ({ id: uniqueId("method"), visibility: "public", name: "method", returnType: "void", parameters: [] });
function PropertiesPanel({ node, onUpdate, onDelete }) {
  if (!node) return <aside className="properties-panel empty-panel"><div className="eyebrow">INSPECTOR</div><p>Select a class on the canvas to edit it.</p></aside>;
  const updateItem = (section, id, key, value) => onUpdate({ [section]: node.data[section].map((item) => item.id === id ? { ...item, [key]: value } : item) });
  return <aside className="properties-panel"><div className="eyebrow">INSPECTOR / CLASS</div><label>Class name<input aria-label="Class name" value={node.data.name} placeholder="Class name" onChange={(event) => onUpdate({ name: event.target.value })} /></label><div className="panel-heading"><span>Attributes</span><button title="Add attribute" aria-label="Add attribute" onClick={() => onUpdate({ attributes: [...node.data.attributes, makeAttribute()] })}><Plus size={15} /></button></div>{node.data.attributes.map((item) => <div className="property-row" key={item.id}><select aria-label={`Visibility for ${item.name || "attribute"}`} value={item.visibility} onChange={(event) => updateItem("attributes", item.id, "visibility", event.target.value)}><option value="private">-</option><option value="public">+</option><option value="protected">#</option><option value="package">~</option></select><input aria-label="Attribute name" value={item.name} placeholder="name" onChange={(event) => updateItem("attributes", item.id, "name", event.target.value)} /><input aria-label="Attribute type" value={item.type} placeholder="type" onChange={(event) => updateItem("attributes", item.id, "type", event.target.value)} /><button title="Delete attribute" aria-label="Delete attribute" onClick={() => onUpdate({ attributes: node.data.attributes.filter((entry) => entry.id !== item.id) })}><Trash2 size={13} /></button></div>)}<div className="panel-heading"><span>Methods</span><button title="Add method" aria-label="Add method" onClick={() => onUpdate({ methods: [...node.data.methods, makeMethod()] })}><Plus size={15} /></button></div>{node.data.methods.map((item) => <div className="property-row method-row" key={item.id}><select aria-label={`Visibility for ${item.name || "method"}`} value={item.visibility} onChange={(event) => updateItem("methods", item.id, "visibility", event.target.value)}><option value="public">+</option><option value="private">-</option><option value="protected">#</option><option value="package">~</option></select><input aria-label="Method name" value={item.name} placeholder="name" onChange={(event) => updateItem("methods", item.id, "name", event.target.value)} /><input aria-label="Method return type" value={item.returnType} placeholder="type" onChange={(event) => updateItem("methods", item.id, "returnType", event.target.value)} /><button title="Delete method" aria-label="Delete method" onClick={() => onUpdate({ methods: node.data.methods.filter((entry) => entry.id !== item.id) })}><Trash2 size={13} /></button></div>)}<button className="delete-class" onClick={onDelete}><Trash2 size={14} /> Delete class</button></aside>;
}

export default PropertiesPanel;

