
import { Plus, Trash2 } from "lucide-react";
const makeAttribute = () => ({ id: `attr-${Date.now()}`, visibility: "private", name: "field", type: "String" });
const makeMethod = () => ({ id: `method-${Date.now()}`, visibility: "public", name: "method", returnType: "void", parameters: [] });
function PropertiesPanel({ node, onUpdate, onDelete }) {
  if (!node) return <aside className="properties-panel empty-panel"><div className="eyebrow">INSPECTOR</div><p>Select a class on the canvas to edit it.</p></aside>;
  const updateItem = (section, id, key, value) => onUpdate({ [section]: node.data[section].map((item) => item.id === id ? { ...item, [key]: value } : item) });
  return <aside className="properties-panel"><div className="eyebrow">INSPECTOR / CLASS</div><label>Class name<input value={node.data.name} onChange={(event) => onUpdate({ name: event.target.value })} /></label><div className="panel-heading"><span>Attributes</span><button title="Add attribute" onClick={() => onUpdate({ attributes: [...node.data.attributes, makeAttribute()] })}><Plus size={15} /></button></div>{node.data.attributes.map((item) => <div className="property-row" key={item.id}><select value={item.visibility} onChange={(event) => updateItem("attributes", item.id, "visibility", event.target.value)}><option value="private">-</option><option value="public">+</option><option value="protected">#</option><option value="package">~</option></select><input value={item.name} onChange={(event) => updateItem("attributes", item.id, "name", event.target.value)} /><input value={item.type} onChange={(event) => updateItem("attributes", item.id, "type", event.target.value)} /><button onClick={() => onUpdate({ attributes: node.data.attributes.filter((entry) => entry.id !== item.id) })}><Trash2 size={13} /></button></div>)}<div className="panel-heading"><span>Methods</span><button title="Add method" onClick={() => onUpdate({ methods: [...node.data.methods, makeMethod()] })}><Plus size={15} /></button></div>{node.data.methods.map((item) => <div className="property-row method-row" key={item.id}><select value={item.visibility} onChange={(event) => updateItem("methods", item.id, "visibility", event.target.value)}><option value="public">+</option><option value="private">-</option><option value="protected">#</option><option value="package">~</option></select><input value={item.name} onChange={(event) => updateItem("methods", item.id, "name", event.target.value)} /><input value={item.returnType} onChange={(event) => updateItem("methods", item.id, "returnType", event.target.value)} /><button onClick={() => onUpdate({ methods: node.data.methods.filter((entry) => entry.id !== item.id) })}><Trash2 size={13} /></button></div>)}<button className="delete-class" onClick={onDelete}><Trash2 size={14} /> Delete class</button></aside>;
}

export default PropertiesPanel;

