require("dotenv").config();
const path = require("path"), express = require("express"), mysql = require("mysql2/promise"), bcrypt = require("bcrypt"), session = require("express-session");
const app = express(), PORT = Number(process.env.PORT) || 3000, dbName = process.env.DB_NAME || "booknest";
if (!/^[A-Za-z0-9_]+$/.test(dbName)) throw new Error("DB_NAME contains invalid characters.");
const options = { host: process.env.DB_HOST || "localhost", user: process.env.DB_USER || "root", password: process.env.DB_PASSWORD || "", port: Number(process.env.DB_PORT) || 3306, waitForConnections: true, connectionLimit: 10 };
let db;
app.use(express.urlencoded({ extended: true })); app.use(express.json());
app.use(session({ secret: process.env.SESSION_SECRET || "development-secret-change-me", resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 86400000 } }));
app.use(express.static(path.join(__dirname, "public")));
const samples = [
 ["The Alchemist","Paulo Coelho","Fiction",399,"https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg","A timeless story about pursuing a personal legend."],
 ["Atomic Habits","James Clear","Self Help",549,"https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg","Small changes that create remarkable results."],
 ["Rich Dad Poor Dad","Robert T. Kiyosaki","Finance",449,"https://covers.openlibrary.org/b/isbn/9781612681139-L.jpg","Lessons about money, investing, and financial independence."],
 ["The Psychology of Money","Morgan Housel","Finance",499,"https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg","Timeless lessons on wealth, greed, and happiness."],
 ["Clean Code","Robert C. Martin","Technology",699,"https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg","A handbook of agile software craftsmanship."],
 ["Harry Potter and the Philosopher's Stone","J. K. Rowling","Fantasy",599,"https://covers.openlibrary.org/b/isbn/9780747532699-L.jpg","The magical first year at Hogwarts."],
 ["Ikigai","Hector Garcia & Francesc Miralles","Self Help",429,"https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg","The Japanese secret to a long and happy life."],
 ["Think and Grow Rich","Napoleon Hill","Self Help",349,"https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg","Classic principles for personal achievement."]
];
async function prepareDatabase() {
 const admin = await mysql.createConnection(options); await admin.query(`CREATE DATABASE IF NOT EXISTS \`${dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); await admin.end(); db = mysql.createPool({ ...options, database: dbName });
 await db.query("CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");
 await db.query("CREATE TABLE IF NOT EXISTS books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL UNIQUE, author VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL, price DECIMAL(10,2) NOT NULL, image VARCHAR(500), description TEXT) ENGINE=InnoDB");
 await db.query("CREATE TABLE IF NOT EXISTS transactions (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, total_amount DECIMAL(10,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'completed', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB");
 await db.query("CREATE TABLE IF NOT EXISTS transaction_items (id INT AUTO_INCREMENT PRIMARY KEY, transaction_id INT NOT NULL, book_id INT NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(10,2) NOT NULL, CONSTRAINT fk_items_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id), CONSTRAINT fk_items_book FOREIGN KEY (book_id) REFERENCES books(id)) ENGINE=InnoDB");
 const [[{ count }]] = await db.query("SELECT COUNT(*) AS count FROM books"); if (!count) await db.query("INSERT INTO books (title, author, category, price, image, description) VALUES ?", [samples]);
}
const view = name => (req, res) => res.sendFile(path.join(__dirname, "views", name));
app.get("/", view("index.html")); app.get("/catalogue", view("catalogue.html")); app.get("/cart", view("cart.html")); app.get("/orders", view("orders.html")); app.get("/register", view("register.html")); app.get("/login", view("login.html"));
const requireLogin = (req,res,next) => req.session.user ? next() : res.status(401).json({error:"Please login to use your cart."});
const validId = value => Number.isSafeInteger(Number(value)) && Number(value) > 0;
app.get("/api/session", (req,res) => res.json({loggedIn:Boolean(req.session.user),user:req.session.user || null}));
app.get("/api/books", async (req,res) => { try { const [rows]=await db.query("SELECT id,title,author,category,price,image,description FROM books ORDER BY id"); res.json(rows); } catch (e) { console.error(e.message);res.status(500).json({error:"Books are temporarily unavailable."}); } });
app.get("/api/cart",requireLogin,(req,res)=>res.json(req.session.cart||[]));
app.post("/api/cart",requireLogin,async(req,res)=>{ const id=Number(req.body.bookId); if(!validId(id)) return res.status(400).json({error:"Invalid book."}); try { const [rows]=await db.query("SELECT id,title,author,price,image FROM books WHERE id = ?",[id]); if(!rows.length)return res.status(404).json({error:"Book not found."}); const cart=req.session.cart||[], item=cart.find(x=>x.book.id===id); if(item)item.quantity++;else cart.push({book:rows[0],quantity:1});req.session.cart=cart;res.status(201).json({message:"Added to cart.",cart}); }catch(e){console.error(e.message);res.status(500).json({error:"Could not add this book to your cart."});} });
app.patch("/api/cart/:bookId",requireLogin,(req,res)=>{const id=Number(req.params.bookId),q=Number(req.body.quantity),cart=req.session.cart||[];if(!validId(id)||!Number.isInteger(q))return res.status(400).json({error:"Invalid cart update."});if(!cart.some(x=>x.book.id===id))return res.status(404).json({error:"Cart item not found."});req.session.cart=q<1?cart.filter(x=>x.book.id!==id):cart.map(x=>x.book.id===id?{...x,quantity:q}:x);res.json(req.session.cart);});
app.delete("/api/cart/:bookId",requireLogin,(req,res)=>{const id=Number(req.params.bookId),cart=req.session.cart||[];if(!validId(id))return res.status(400).json({error:"Invalid book."});if(!cart.some(x=>x.book.id===id))return res.status(404).json({error:"Cart item not found."});req.session.cart=cart.filter(x=>x.book.id!==id);res.status(204).end();});
app.post("/api/checkout",requireLogin,async(req,res)=>{const cart=req.session.cart||[];if(!cart.length)return res.status(400).json({error:"Your cart is empty."});if(cart.some(x=>!validId(x.book.id)||!Number.isInteger(x.quantity)||x.quantity<1))return res.status(400).json({error:"Your cart contains an invalid item."});const c=await db.getConnection();try{await c.beginTransaction();const ids=cart.map(x=>x.book.id),[books]=await c.query("SELECT id,price FROM books WHERE id IN (?)",[ids]);if(books.length!==ids.length)throw new Error("A book no longer exists.");const prices=new Map(books.map(x=>[x.id,Number(x.price)])),total=cart.reduce((s,x)=>s+prices.get(x.book.id)*x.quantity,0),[order]=await c.query("INSERT INTO transactions (user_id,total_amount,status) VALUES (?,?,'completed')",[req.session.user.id,total]);await c.query("INSERT INTO transaction_items (transaction_id,book_id,quantity,unit_price) VALUES ?",[cart.map(x=>[order.insertId,x.book.id,x.quantity,prices.get(x.book.id)])]);await c.commit();req.session.cart=[];res.status(201).json({message:"Purchase completed successfully!",transactionId:order.insertId,total});}catch(e){await c.rollback();console.error("Checkout failed:",e.message);res.status(500).json({error:"Could not complete your purchase. Please try again."});}finally{c.release();}});
app.get("/api/orders",requireLogin,async(req,res)=>{try{const [rows]=await db.query("SELECT t.id transaction_id,t.total_amount,t.status,t.created_at,ti.book_id,ti.quantity,ti.unit_price,b.title,b.author,b.image FROM transactions t JOIN transaction_items ti ON ti.transaction_id=t.id JOIN books b ON b.id=ti.book_id WHERE t.user_id=? ORDER BY t.created_at DESC,ti.id ASC",[req.session.user.id]);const orders=[];for(const r of rows){let o=orders.find(x=>x.id===r.transaction_id);if(!o){o={id:r.transaction_id,total:Number(r.total_amount),status:r.status,createdAt:r.created_at,items:[]};orders.push(o);}o.items.push({bookId:r.book_id,title:r.title,author:r.author,image:r.image,quantity:r.quantity,unitPrice:Number(r.unit_price)});}res.json(orders);}catch(e){console.error(e.message);res.status(500).json({error:"Could not load your order history."});}});
const validEmail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
app.post("/register",async(req,res)=>{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),confirm=String(req.body.confirmPassword||""),fail=m=>res.redirect("/register?error="+encodeURIComponent(m));if(name.length<2||name.length>100)return fail("Please enter a valid name.");if(!validEmail(email))return fail("Please enter a valid email address.");if(password.length<8)return fail("Password must be at least 8 characters.");if(password!==confirm)return fail("Passwords do not match.");try{const [old]=await db.query("SELECT id FROM users WHERE email=?",[email]);if(old.length)return fail("This email is already registered.");const [r]=await db.query("INSERT INTO users (name,email,password) VALUES (?,?,?)",[name,email,await bcrypt.hash(password,12)]);req.session.user={id:r.insertId,name,email};res.redirect("/catalogue?success="+encodeURIComponent("Account created. Welcome to BookNest!"));}catch(e){console.error(e.message);fail("We could not create your account. Please try again.");}});
app.post("/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),fail=m=>res.redirect("/login?error="+encodeURIComponent(m));if(!email||!password)return fail("Please enter your email and password.");try{const [users]=await db.query("SELECT id,name,email,password FROM users WHERE email=?",[email]);if(!users.length||!(await bcrypt.compare(password,users[0].password)))return fail("Invalid email or password.");const u=users[0];req.session.user={id:u.id,name:u.name,email:u.email};res.redirect("/catalogue?success="+encodeURIComponent(`Welcome back, ${u.name}!`));}catch(e){console.error(e.message);fail("We could not sign you in. Please try again.");}});
app.get("/logout",(req,res)=>req.session.destroy(e=>{if(e)return res.redirect("/?error="+encodeURIComponent("Could not log you out."));res.clearCookie("connect.sid");res.redirect("/?success="+encodeURIComponent("You have been logged out."));}));
prepareDatabase().then(()=>app.listen(PORT,()=>console.log(`BookNest is running at http://localhost:${PORT}`))).catch(e=>{console.error("Database setup failed:",e.message);process.exit(1);});
